### ISSUE TITLE
Bundler eval_gemfile not supported

### ISSUE THREAD

**Issue by olleolleolle** [gocardless/bump#104]
Bundler supports the [eval_gemfile](http://www.rubydoc.info/github/carlhuda/bundler/Bundler%2FDsl%3Aeval_gemfile) DSL command, which allows other files to be read from a path "as if they were in the Gemfile".

Here's what output looks like when that happens:

```
14:26:26 worker.1 | 2016-07-18T12:26:26.408Z 72453 TID-ow8jjmiyo WARN: SharedHelpers::ChildProcessFailed: Child process raised Bundler::Dsl::DSLError with message: 
14:26:26 worker.1 | [!] There was an error parsing `Gemfile`: 
14:26:26 worker.1 | [!] There was an error parsing `Gemfile.shared`: No such file or directory @ rb_sysopen - Gemfile.shared. Bundler cannot continue.
14:26:26 worker.1 | . Bundler cannot continue.
14:26:26 worker.1 | 
14:26:26 worker.1 |  #  from /Users/olle/opensource/bump/tmp/bump_20160718-72453-1nbj6gy/Gemfile:1
14:26:26 worker.1 |  #  -------------------------------------------
14:26:26 worker.1 |  >  eval_gemfile 'Gemfile.shared'
14:26:26 worker.1 |  #  
14:26:26 worker.1 |  #  -------------------------------------------
14:26:26 worker.1 | 
14:26:26 worker.1 | 2016-07-18T12:26:26.408Z 72453 TID-ow8jjmiyo WARN: /Users/olle/opensource/bump/lib/shared_helpers.rb:48:in `in_a_forked_process'
14:26:26 worker.1 | /Users/olle/opensource/bump/app/dependency_file_updaters/ruby.rb:75:in `block in build_updated_gemfile_lock'
14:26:26 worker.1 | /Users/olle/opensource/bump/lib/shared_helpers.rb:22:in `block in in_a_temporary_directory'
```

Modeling neighboring Gemfiles involved in `eval_gemfile` is what this feature request issue is about.

http://www.alliants.com/blog/modular-composable-gemfiles

**Comment by greysteil** [comment]
@olleolleolle - thinking about adding support for this to [Dependabot Core](https://github.com/dependabot/dependabot-core). Do you have an repo in mind that you were thinking of it for, ideally open-source? We already [recursively fetch Python requirement.txt files](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_fetchers/python/pip.rb#L35-L51) so I'm game for doing the same for Ruby.

**Comment by olleolleolle** [comment]
@greysteil My use-case was closed-source. And, for me, it is no longer current.

**Comment by olleolleolle** [comment]
@greysteil Essentially, two Gemfiles (`Gemfile`, `Gemfile.jruby`), both using a third `Gemfile.shared` with `eval_gemfile`.

**Comment by greysteil** [comment]
👍  I'll wait until someone needs it before adding to Dependabot then. @hmac - can you close this in the meantime?

**Comment by olleolleolle** [comment]
(I'm happy to retract my feature request.)
