### ISSUE TITLE
How to add repos to check?

### ISSUE THREAD

**Issue by olimart** [gocardless/bump#206]
Hi,
looks promising. I've deployed the app to Heroku but all I can see is sidekiq dashboard.

How do I add repos to monitor? Thanks

**Comment by nickcampbell18** [comment]
Hi @olimart!

Sure, check out this step from the README:

> Once you've deployed, you'll want to click through to Heroku Scheduler in the list of addons and set up a scheduled task to bump your dependencies each day. You can use the ./bin/bump_dependencies_for_repo script to do this:
>
> `bundle exec bin/bump_dependencies_for_repo gocardless/bump ruby`

As an example, here is how we keep bump bumped:

<img width="868" alt="screen shot 2017-05-29 at 19 34 19" src="https://cloud.githubusercontent.com/assets/661795/26559174/dff5ee5e-44a5-11e7-8e7b-33fca6ae0c8d.png">

**Comment by olimart** [comment]
Thanks @nickcampbell18 I get the scheduler thing in Heroku.
What I don't get is how to instruct bump to monitor repo XYZ on GitHub. What am I missing?
Thanks for your help.

**Comment by greysteil** [comment]
@olimart - you just need to replace `gocardless/ruby` with `your/ruby`.

We (Harry and I, the original authors of Bump) have also written [dependabot](https://dependabot.com) if you want a simple interface for adding repos etc.. It's totally free for anything open-source, and always will be.

**Comment by olimart** [comment]
So obvious that I did not even look at the full command you typed into the scheduler. Makes sense now. Thanks.
